package com.UHT.Insight.dao;

import com.UHT.Insight.pojo.gameGrade;
import com.UHT.Insight.pojo.gameGradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gameGradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    long countByExample(gameGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int deleteByExample(gameGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int deleteByPrimaryKey(Integer gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int insert(gameGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int insertSelective(gameGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    List<gameGrade> selectByExample(gameGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    gameGrade selectByPrimaryKey(Integer gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") gameGrade record, @Param("example") gameGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int updateByExample(@Param("record") gameGrade record, @Param("example") gameGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int updateByPrimaryKeySelective(gameGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int updateByPrimaryKey(gameGrade record);
}