package com.UHT.Insight.dao;

import com.UHT.Insight.pojo.Uuser;
import com.UHT.Insight.pojo.UuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuser
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    long countByExample(UuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuser
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int deleteByExample(UuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuser
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int deleteByPrimaryKey(Integer uuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuser
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int insert(Uuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuser
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int insertSelective(Uuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuser
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    List<Uuser> selectByExample(UuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuser
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    Uuser selectByPrimaryKey(Integer uuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuser
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") Uuser record, @Param("example") UuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuser
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int updateByExample(@Param("record") Uuser record, @Param("example") UuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuser
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int updateByPrimaryKeySelective(Uuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuser
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    int updateByPrimaryKey(Uuser record);
}