package com.UHT.Insight.pojo;

import java.util.ArrayList;
import java.util.List;

public class gameGradeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public gameGradeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGIdIsNull() {
            addCriterion("G_ID is null");
            return (Criteria) this;
        }

        public Criteria andGIdIsNotNull() {
            addCriterion("G_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGIdEqualTo(Integer value) {
            addCriterion("G_ID =", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotEqualTo(Integer value) {
            addCriterion("G_ID <>", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThan(Integer value) {
            addCriterion("G_ID >", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("G_ID >=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThan(Integer value) {
            addCriterion("G_ID <", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThanOrEqualTo(Integer value) {
            addCriterion("G_ID <=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdIn(List<Integer> values) {
            addCriterion("G_ID in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotIn(List<Integer> values) {
            addCriterion("G_ID not in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdBetween(Integer value1, Integer value2) {
            addCriterion("G_ID between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotBetween(Integer value1, Integer value2) {
            addCriterion("G_ID not between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeIsNull() {
            addCriterion("TapTap_GADE is null");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeIsNotNull() {
            addCriterion("TapTap_GADE is not null");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeEqualTo(Float value) {
            addCriterion("TapTap_GADE =", value, "taptapGade");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeNotEqualTo(Float value) {
            addCriterion("TapTap_GADE <>", value, "taptapGade");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeGreaterThan(Float value) {
            addCriterion("TapTap_GADE >", value, "taptapGade");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeGreaterThanOrEqualTo(Float value) {
            addCriterion("TapTap_GADE >=", value, "taptapGade");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeLessThan(Float value) {
            addCriterion("TapTap_GADE <", value, "taptapGade");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeLessThanOrEqualTo(Float value) {
            addCriterion("TapTap_GADE <=", value, "taptapGade");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeIn(List<Float> values) {
            addCriterion("TapTap_GADE in", values, "taptapGade");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeNotIn(List<Float> values) {
            addCriterion("TapTap_GADE not in", values, "taptapGade");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeBetween(Float value1, Float value2) {
            addCriterion("TapTap_GADE between", value1, value2, "taptapGade");
            return (Criteria) this;
        }

        public Criteria andTaptapGadeNotBetween(Float value1, Float value2) {
            addCriterion("TapTap_GADE not between", value1, value2, "taptapGade");
            return (Criteria) this;
        }

        public Criteria andRGWeightIsNull() {
            addCriterion("R_G_WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andRGWeightIsNotNull() {
            addCriterion("R_G_WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andRGWeightEqualTo(Double value) {
            addCriterion("R_G_WEIGHT =", value, "rGWeight");
            return (Criteria) this;
        }

        public Criteria andRGWeightNotEqualTo(Double value) {
            addCriterion("R_G_WEIGHT <>", value, "rGWeight");
            return (Criteria) this;
        }

        public Criteria andRGWeightGreaterThan(Double value) {
            addCriterion("R_G_WEIGHT >", value, "rGWeight");
            return (Criteria) this;
        }

        public Criteria andRGWeightGreaterThanOrEqualTo(Double value) {
            addCriterion("R_G_WEIGHT >=", value, "rGWeight");
            return (Criteria) this;
        }

        public Criteria andRGWeightLessThan(Double value) {
            addCriterion("R_G_WEIGHT <", value, "rGWeight");
            return (Criteria) this;
        }

        public Criteria andRGWeightLessThanOrEqualTo(Double value) {
            addCriterion("R_G_WEIGHT <=", value, "rGWeight");
            return (Criteria) this;
        }

        public Criteria andRGWeightIn(List<Double> values) {
            addCriterion("R_G_WEIGHT in", values, "rGWeight");
            return (Criteria) this;
        }

        public Criteria andRGWeightNotIn(List<Double> values) {
            addCriterion("R_G_WEIGHT not in", values, "rGWeight");
            return (Criteria) this;
        }

        public Criteria andRGWeightBetween(Double value1, Double value2) {
            addCriterion("R_G_WEIGHT between", value1, value2, "rGWeight");
            return (Criteria) this;
        }

        public Criteria andRGWeightNotBetween(Double value1, Double value2) {
            addCriterion("R_G_WEIGHT not between", value1, value2, "rGWeight");
            return (Criteria) this;
        }

        public Criteria andCoreGradeIsNull() {
            addCriterion("CORE_GRADE is null");
            return (Criteria) this;
        }

        public Criteria andCoreGradeIsNotNull() {
            addCriterion("CORE_GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andCoreGradeEqualTo(Double value) {
            addCriterion("CORE_GRADE =", value, "coreGrade");
            return (Criteria) this;
        }

        public Criteria andCoreGradeNotEqualTo(Double value) {
            addCriterion("CORE_GRADE <>", value, "coreGrade");
            return (Criteria) this;
        }

        public Criteria andCoreGradeGreaterThan(Double value) {
            addCriterion("CORE_GRADE >", value, "coreGrade");
            return (Criteria) this;
        }

        public Criteria andCoreGradeGreaterThanOrEqualTo(Double value) {
            addCriterion("CORE_GRADE >=", value, "coreGrade");
            return (Criteria) this;
        }

        public Criteria andCoreGradeLessThan(Double value) {
            addCriterion("CORE_GRADE <", value, "coreGrade");
            return (Criteria) this;
        }

        public Criteria andCoreGradeLessThanOrEqualTo(Double value) {
            addCriterion("CORE_GRADE <=", value, "coreGrade");
            return (Criteria) this;
        }

        public Criteria andCoreGradeIn(List<Double> values) {
            addCriterion("CORE_GRADE in", values, "coreGrade");
            return (Criteria) this;
        }

        public Criteria andCoreGradeNotIn(List<Double> values) {
            addCriterion("CORE_GRADE not in", values, "coreGrade");
            return (Criteria) this;
        }

        public Criteria andCoreGradeBetween(Double value1, Double value2) {
            addCriterion("CORE_GRADE between", value1, value2, "coreGrade");
            return (Criteria) this;
        }

        public Criteria andCoreGradeNotBetween(Double value1, Double value2) {
            addCriterion("CORE_GRADE not between", value1, value2, "coreGrade");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gamegrade
     *
     * @mbg.generated do_not_delete_during_merge Sat Jan 11 18:41:37 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gamegrade
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}