package com.UHT.Insight.pojo;

public class gameGrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gamegrade.G_ID
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    private Integer gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gamegrade.TapTap_GADE
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    private Float taptapGade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gamegrade.R_G_WEIGHT
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    private Double rGWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gamegrade.CORE_GRADE
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    private Double coreGrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gamegrade.G_ID
     *
     * @return the value of gamegrade.G_ID
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gamegrade.G_ID
     *
     * @param gId the value for gamegrade.G_ID
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gamegrade.TapTap_GADE
     *
     * @return the value of gamegrade.TapTap_GADE
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public Float getTaptapGade() {
        return taptapGade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gamegrade.TapTap_GADE
     *
     * @param taptapGade the value for gamegrade.TapTap_GADE
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setTaptapGade(Float taptapGade) {
        this.taptapGade = taptapGade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gamegrade.R_G_WEIGHT
     *
     * @return the value of gamegrade.R_G_WEIGHT
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public Double getrGWeight() {
        return rGWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gamegrade.R_G_WEIGHT
     *
     * @param rGWeight the value for gamegrade.R_G_WEIGHT
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setrGWeight(Double rGWeight) {
        this.rGWeight = rGWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gamegrade.CORE_GRADE
     *
     * @return the value of gamegrade.CORE_GRADE
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public Double getCoreGrade() {
        return coreGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gamegrade.CORE_GRADE
     *
     * @param coreGrade the value for gamegrade.CORE_GRADE
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setCoreGrade(Double coreGrade) {
        this.coreGrade = coreGrade;
    }
}