package com.UHT.Insight.pojo;

public class Kmean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Kmean.ID
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Kmean.G_ID
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    private Integer gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Kmean.cindex
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    private String cindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Kmean.label
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    private Integer label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Kmean.px
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    private String px;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Kmean.py
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    private String py;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Kmean.ID
     *
     * @return the value of Kmean.ID
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Kmean.ID
     *
     * @param id the value for Kmean.ID
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Kmean.G_ID
     *
     * @return the value of Kmean.G_ID
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Kmean.G_ID
     *
     * @param gId the value for Kmean.G_ID
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Kmean.cindex
     *
     * @return the value of Kmean.cindex
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public String getCindex() {
        return cindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Kmean.cindex
     *
     * @param cindex the value for Kmean.cindex
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public void setCindex(String cindex) {
        this.cindex = cindex == null ? null : cindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Kmean.label
     *
     * @return the value of Kmean.label
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public Integer getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Kmean.label
     *
     * @param label the value for Kmean.label
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public void setLabel(Integer label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Kmean.px
     *
     * @return the value of Kmean.px
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public String getPx() {
        return px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Kmean.px
     *
     * @param px the value for Kmean.px
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public void setPx(String px) {
        this.px = px == null ? null : px.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Kmean.py
     *
     * @return the value of Kmean.py
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public String getPy() {
        return py;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Kmean.py
     *
     * @param py the value for Kmean.py
     *
     * @mbg.generated Sat Feb 22 18:06:28 CST 2020
     */
    public void setPy(String py) {
        this.py = py == null ? null : py.trim();
    }
}