package com.UHT.Insight.pojo;

public class Uuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuser.UU_ID
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    private Integer uuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuser.UU_NAME
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    private String uuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuser.UU_PHONE
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    private String uuPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuser.PASSWORD
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuser.SEX
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuser.COMPANY
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuser.P_COMMENT
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    private String pComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuser.UU_ID
     *
     * @return the value of uuser.UU_ID
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public Integer getUuId() {
        return uuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuser.UU_ID
     *
     * @param uuId the value for uuser.UU_ID
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setUuId(Integer uuId) {
        this.uuId = uuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuser.UU_NAME
     *
     * @return the value of uuser.UU_NAME
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public String getUuName() {
        return uuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuser.UU_NAME
     *
     * @param uuName the value for uuser.UU_NAME
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setUuName(String uuName) {
        this.uuName = uuName == null ? null : uuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuser.UU_PHONE
     *
     * @return the value of uuser.UU_PHONE
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public String getUuPhone() {
        return uuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuser.UU_PHONE
     *
     * @param uuPhone the value for uuser.UU_PHONE
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setUuPhone(String uuPhone) {
        this.uuPhone = uuPhone == null ? null : uuPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuser.PASSWORD
     *
     * @return the value of uuser.PASSWORD
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuser.PASSWORD
     *
     * @param password the value for uuser.PASSWORD
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuser.SEX
     *
     * @return the value of uuser.SEX
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuser.SEX
     *
     * @param sex the value for uuser.SEX
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuser.COMPANY
     *
     * @return the value of uuser.COMPANY
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuser.COMPANY
     *
     * @param company the value for uuser.COMPANY
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuser.P_COMMENT
     *
     * @return the value of uuser.P_COMMENT
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public String getpComment() {
        return pComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuser.P_COMMENT
     *
     * @param pComment the value for uuser.P_COMMENT
     *
     * @mbg.generated Sat Jan 11 18:41:37 CST 2020
     */
    public void setpComment(String pComment) {
        this.pComment = pComment == null ? null : pComment.trim();
    }
}